### ISSUE TITLE
Create UML diagrams for LED class and BTS7960_Motordriver class

### ISSUE THREAD

**Issue by 1337encrypted** [1337encrypted/BTS7960_TH9x#1]
1. Clone the repository using `git clone https://github.com/1337encrypted/BTS7960_TH9x.git` on your local machine
1. Use draw.io to draw the diagrams for **LED** class and **BTS7960_Motordriver** class
1. Create a folder called **assets** and save the files there
1. Create a **README.md** file and display the UML diagram under the heading "UML diagrams of classes"
1. After making the changes:

-   `git add .`
-   `git commit -m <your message>`
-   `git push origin main`

6. Lastly close this issue after doing everything

**Comment by shradhapatil22** [comment]
Worked on the UML diagrams for LED and Motordriver classes. Commit ID 8ad53732
