### ISSUE TITLE
Create UML diagrams for Buzzer class and FlySkyIBus class

### ISSUE THREAD

**Issue by 1337encrypted** [1337encrypted/BTS7960_TH9x#2]
1. Clone the repository using git clone `https://github.com/1337encrypted/BTS7960_TH9x.git` on your local machine
1. Use draw.io to draw the diagrams for **Buzzer** class and **FlySkyIBus** class
1. Save all the files called **assets**
1. Edit the **README.md** file and display the UML diagram under the heading "UML diagrams of classes"
1. After making the changes:
-  `git add .`
-  `git commit -m <your message>`
-  `git push origin main`
6. Lastly close this issue after doing everything

**Comment by srushtim-01** [comment]
Have added the Buzzer and FlySkylbus class diagrams.

**Comment by srushtim-01** [comment]
Have added the UML diagrams
