### ISSUE TITLE
Create UML Use case diagram

### ISSUE THREAD

**Issue by 1337encrypted** [1337encrypted/BTS7960_TH9x#4]
## Actors:
Operator: The person controlling the car remotely
Car: The four-wheel buggy car being controlled remotely

## Use Cases:
1. Control speed and direction: The operator uses radio control to control the speed and direction of the car.
2. Navigate: The operator uses the radio control to navigate the car through different terrains
3. Test: The operator uses the radio control to test the car's capabilities and performance in different conditions
4. Research and Exploration: The operator uses radio control to conduct research and explore remote areas.
5. Remote Control Setup: The operator can set up and configure the remote control for the whip

## Use case relationships:
1. The control speed and direction use case includes the Navigate use case, meaning that in order to control the speed and direction, the car must first be able to navigate.
2. Navigate use case extends the Test use case, meaning that the testing functionality is added to the navigate use case, allowing the operator to test the car's ability to navigate before using it in a real-world scenario.
3. The research and Exploration use case generalizes the Navigate use case, meaning that the Research and Exploration use case is a more specialized version of the Navigate use case, with the added functionality of conducting research and exploring remote areas.
4. The Remote Control Setup use case generalizes the Navigate use case, meaning that the Remote Control Setup use case is a more specialized version of the Navigate use case, with the added functionality of setting up and configuring the remote control for the car.

**Comment by shradhapatil22** [comment]
added use case diagram
